#!/bin/sh -x
[ -z "$2" ] && echo "Error: should be run by odhcpc6c" && exit 1
PROTO=74
EXT_IFACE=eth3

#env >> /tmp/odhcpdscript.log
#echo "---" >> /tmp/odhcpdscript.log

update_resolv() {
	local device="$1"
	local dns="$2"
	
	(
		flock 9
		grep -v "#odhcp6c:$device:" /etc/resolv.conf > /tmp/resolv.conf.tmp
		for c in $dns; do
			echo "nameserver $c #odhcp6c:$device:" >> /tmp/resolv.conf.tmp
		done
		mv /tmp/resolv.conf.tmp /etc/resolv.conf
		chmod 0644 /etc/resolv.conf
	) 9>/tmp/resolv.conf.lock
	rm -f /tmp/resolv.conf.lock /tmp/resolv.conf.tmp
}

setup_interface () {
	local device="$1"

	# Merge RA-DNS
	for radns in $RA_DNS; do
		local duplicate=0
		for dns in $RDNSS; do
			[ "$radns" = "$dns" ] && duplicate=1
		done
		[ "$duplicate" = 0 ] && RDNSS="$RDNSS $radns"
	done

	local dnspart=""
	for dns in $RDNSS; do
		if [ -z "$dnspart" ]; then
			dnspart="\"$dns\""
		else
			dnspart="$dnspart, \"$dns\""
		fi
	done

	update_resolv "$device" "$dns"

	local prefixpart=""
	for entry in $PREFIXES; do
		local addr="${entry%%,*}"
                entry="${entry#*,}"
                local preferred="${entry%%,*}"
                entry="${entry#*,}"
                local valid="${entry%%,*}"
                entry="${entry#*,}"
		[ "$entry" = "$valid" ] && entry=

		local class=""
		local excluded=""

		while [ -n "$entry" ]; do
			local key="${entry%%=*}"
                	entry="${entry#*=}"
			local val="${entry%%,*}"
                	entry="${entry#*,}"
			[ "$entry" = "$val" ] && entry=

			if [ "$key" = "class" ]; then
				class=", \"class\": $val"
			elif [ "$key" = "excluded" ]; then
				excluded=", \"excluded\": \"$val\""
			fi
		done

		local prefix="{\"address\": \"$addr\", \"preferred\": $preferred, \"valid\": $valid $class $excluded}"
		
		if [ -z "$prefixpart" ]; then
			prefixpart="$prefix"
		else
			prefixpart="$prefixpart, $prefix"
		fi

		# TODO: delete this somehow when the prefix disappears
		ip -6 route replace unreachable "$addr" proto $PROTO
	done

	ip -6 route flush dev "$device" proto $PROTO
	#ip -6 address flush dev "$device" scope global # just let it expire

	# Merge addresses
	for entry in $RA_ADDRESSES; do
		local duplicate=0
		local addr="${entry%%/*}"
		for dentry in $ADDRESSES; do
			local daddr="${dentry%%/*}"
			[ "$addr" = "$daddr" ] && duplicate=1
		done
		[ "$duplicate" = "0" ] && ADDRESSES="$ADDRESSES $entry"
	done

	for entry in $ADDRESSES; do
		local addr="${entry%%,*}"
		entry="${entry#*,}"
		local preferred="${entry%%,*}"
		entry="${entry#*,}"
		local valid="${entry%%,*}"
		ip -6 address replace "$addr" dev "$device" preferred_lft "$preferred" valid_lft "$valid"
	done

	for entry in $RA_ROUTES; do
		local addr="${entry%%,*}"
		local mask=${addr#*/}
		entry="${entry#*,}"
		local gw="${entry%%,*}"
		entry="${entry#*,}"
		local valid="${entry%%,*}"
		entry="${entry#*,}"
		local metric="${entry%%,*}"

		if [ -n "$gw" ]; then
			:
			#ip -6 route replace "$addr" via "$gw" metric "$metric" dev "$device" from "::/128" proto $PROTO
		else
			ip -6 route replace "$addr" metric "$metric" dev "$device" proto $PROTO
		fi
	

		# Add a covering source specific route from the RA
		local hadprefix=0
		for prefix in $PREFIXES; do
			local paddr="${prefix%%,*}"
			[ -n "$gw" ] && ip -6 route replace "$addr" via "$gw" metric "$metric" dev "$device" from "$paddr" proto $PROTO
			hadprefix=1
		# Add a local network
			local addr1="${paddr%%/*}"
			ip -6 address replace "${addr1}1/64" dev "$EXT_IFACE" preferred_lft "$preferred" valid_lft "$valid"
		done
		if [ $hadprefix = 1 -a $mask  -lt 64 -a $mask -gt 0 -a -n "$gw" ] 
		then
			ip -6 route replace unreachable "$addr" proto $PROTO
#			ip -6 route replace default via "$gw" metric "$metric" dev "$device" from "$addr" proto $PROTO
		fi
	done
}

teardown_interface() {
	local device="$1"
	ip -6 route flush dev "$device" proto $PROTO 
	# ip -6 route flush proto $PROTO Will flush all the unreachable routes on exit
	#ip -6 address flush dev "$device" scope global
	update_resolv "$device" ""
}

(
	flock 9
	case "$2" in
		bound)
			teardown_interface "$1"
			setup_interface "$1"
		;;
		informed|updated|rebound|ra-updated)
			setup_interface "$1"
		;;
		unbound)
			teardown_interface "$1"
		;;
		stopped)
			teardown_interface "$1"
			ip -6 route flush proto $PROTO
		;;
		started)
			teardown_interface "$1"
		;;
	esac

	# user rules
	[ -f /etc/odhcp6c.user ] && . /etc/odhcp6c.user
) 9>/tmp/odhcp6c.lock.$1
rm -f /tmp/odhcp6c.lock.$1
